### ISSUE TITLE
How to delete?can`t find REGISTRY_DATA_DIR.

### ISSUE THREAD

**Issue by Toplife** [burnettk/delete-docker-registry-image#9]
Hi,
delete_docker_registry_image --image localhost:5000/cs/hello-world:8.0
CRITICAL [2016-03-02 21:26:01,938] No repository 'localhost:5000/cs/hello-world:8.0' found in repositories directory /var/lib/docker/repositories
I can`t find REGISTRY_DATA_DIR,pls help...

**Comment by burnettk** [comment]
you want to omit the localhost:5000/ in the image reference. ls
/var/lib/docker/repositories
to get an idea of the structure.

**Comment by Toplife** [comment]
At path of **/var/lib/docker/**
containers  devicemapper  graph  linkgraph.db  repositories-devicemapper  tmp  trust  volumes
no repositories folder...
Any where wrong?

**Comment by burnettk** [comment]
oh, yeah, that's the docker graph location on your host, not your registry data directory. your registry data is wherever you bindmounted it to when you started up your registry. i start my registry with a docker-compose.yml like this:

````
registry:
  # restart: always
  image: registry:2.1.1
  ports:
    - 5000:5000
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
  volumes:
    - /opt/registry_data:/var/lib/registry
````

i'm tell the registry to put its data in the container at /var/lib/registry (i think this is default now, so you can probably omit the REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY line) and then i mount /opt/registry on the host as the volume which persists /var/lib/registry inside the countainer. perhaps you used another location on the host instead of /opt/registry.

if you're still not sure where you put it, you could try this:

````
locate v2/repositories
````
